### ISSUE TITLE
#define WIN10_21H1_EPROCESS_TO_ACTIVEPROCESSLINKS_OFFSET 0x448
是EPROCESS偏移量里的哪个?

### ISSUE THREAD

**Issue by PspExitThread** [Military-axe/HideProcessR0#1]
#define WIN10_21H1_EPROCESS_TO_ACTIVEPROCESSLINKS_OFFSET 0x448
是EPROCESS偏移量里的哪个?

**Comment by Military-axe** [comment]
在 2024-07-02 18:20:35，"KALI_MC" ***@***.***> 写道：

#define WIN10_21H1_EPROCESS_TO_ACTIVEPROCESSLINKS_OFFSET 0x448
是EPROCESS偏移量里的哪个?
